name: countly_flutter_lite
description: Lightweight and stable Flutter SDK for simple analytics integration.
version: 26.1.0-rc.1
homepage: https://countly.com
repository: https://github.com/Countly/countly-sdk-flutter-bridge
issue_tracker: https://github.com/Countly/countly-sdk-flutter-bridge/issues
topics: analytics, flutter, sdk, mobile, countly

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  countly_sdk_dart_core: 26.1.0-rc.3
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  http: ^1.2.2

flutter:
  plugin:
    platforms:
      android:
        package: ly.count.dart.countly_flutter_lite
        pluginClass: CountlyFlutterLitePlugin
      ios:
        pluginClass: CountlyFlutterLitePlugin
